on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: mingc/android-build-box:latest
    steps:
      - run: rm -rf /usr/share/dotnet
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: "gem install bundler:2.2.15"
      - run: "rm -rf node_modules"
      - run: "yarn"
      - run: "npx jetify"
#      - run: "./gradlew clean"
#        working-directory: android/
      - run: "fastlane install_plugins"
        working-directory: android/
      - run: "fastlane build id:${{ secrets.ANDROID_APP_ID }} token:${{ secrets.TOKEN }}"
        working-directory: android/


