on:
  push:
    branches:
      - '*'

jobs:
  build:
    defaults:
      run:
        working-directory: ./app
    runs-on: ubuntu-18.04
    container: mingc/android-build-box:latest
    steps:
#      - run: "gem install bundler:2.2.15"
#      - run: "rm -rf node_modules"
      - run: "yarn"
#      - run: "npx jetify"
#      - run: "./gradlew clean"
#      - run: "fastlane install_plugins"
#      - run: "fastlane build id:${{ secrets.ANDROID_APP_ID }} token:${{ secrets.TOKEN }}"

